x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres/${POSTGRES_DB:-airflow}
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__WEBSERVER__SECRET_KEY=une_cle_tres_secrete_123
    - AIRFLOW__CORE__HOSTNAME_CALLABLE=airflow.utils.net.get_host_ip_address
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./src:/opt/airflow/src
    - ./data:/opt/spark/data
    - ./models:/opt/spark/models
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

x-spark-common: &spark-common
  build:
    context: .
    dockerfile: Dockerfile.spark
  image: spark:3.5.1

services:
  # -------------------------------------
  # 1. KAFKA (Confluent KRaft Mode)
  # -------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka_broker
    ports:
      - "9094:9094"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,EXTERNAL://localhost:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - bigdata-net

  # -------------------------------------
  # 2. APACHE SPARK
  # -------------------------------------
  spark-master:
    <<: *spark-common
    container_name: spark_master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
    volumes:
      - ./data:/opt/spark/data
      - ./models:/opt/spark/models
      - ./src:/opt/spark/src
      - ./data_processing:/opt/spark/data_processing 
    networks:
      - bigdata-net

  spark-worker:
    <<: *spark-common
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark/data
      - ./models:/opt/spark/models
      - ./src:/opt/spark/src
    networks:
      - bigdata-net
    deploy:
      replicas: 2

  # -------------------------------------
  # 3. APACHE AIRFLOW & DATABASE
  # -------------------------------------
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Correction critique pour la persistance
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-airflow}"]
      interval: 5s
      retries: 5
    networks:
      - bigdata-net

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: version
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres/${POSTGRES_DB:-airflow}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_WWW_USER_USERNAME:-admin}
      - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_WWW_USER_PASSWORD:-admin}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bigdata-net

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8081:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - bigdata-net

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - bigdata-net

  # -------------------------------------
  # 4. EXPOSITION REST API & FRONTEND
  # -------------------------------------
  api-recommendation:
    build:
      # On indique le dossier où se trouve l'API
      context: ./src/dashboard
      # On pointe vers le bon Dockerfile
      dockerfile: Dockerfile.api
    container_name: api_recommendation
    ports:
      # On expose le port 8000 de l'API vers le port 8000 de ton Ubuntu
      - "8000:8000"
    environment:
      # Variables d'environnement pour la connexion à la BD
      - API_DB_HOST=postgres
      - API_DB_PORT=5432
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow_pass
    volumes:
      - ./models:/opt/spark/models
    networks:
      # Il doit être sur le même réseau que PostgreSQL et Kafka
      - bigdata-net
    depends_on:
      # Il a besoin de la BD pour fonctionner
      postgres:
        condition: service_healthy

volumes:
  kafka_data:
  postgres_data:

networks:
  bigdata-net:
    driver: bridge
